import {StyleSheet} from 'react-native';

import {DesignSystem} from 'theme/designSystem';

type Metrics = {
  width: number;
  height: number;
};

const createStyles = (design: DesignSystem, metrics: Metrics) => {
  const {spacing, font, radius, icon, safeArea, border, control} = design;
  const isWide = metrics.width >= 760;
  const isCompact = metrics.width < 560;
  const isShort = metrics.height < 620;
  const horizontalPadding = Math.max(spacing.md, safeArea.left + spacing.md);
  const categoryWidth = isWide ? Math.min(250, metrics.width * 0.25) : metrics.width * 0.31;
  const dishImageHeight = isWide ? (isShort ? 120 : 154) : 118;
  const dishCardWidth = isWide ? '31.7%' : isCompact ? '100%' : '48.5%';
  const adminDishCardWidth = isWide ? '32%' : '100%';

  return StyleSheet.create({
    screen: {
      flex: 1,
      backgroundColor: '#030304',
      paddingTop: safeArea.top + spacing.xs,
      paddingBottom: safeArea.bottom,
      overflow: 'hidden',
    },
    screenGlowTop: {
      position: 'absolute',
      top: -metrics.height * 0.15,
      right: -metrics.width * 0.22,
      width: metrics.width * 0.72,
      height: metrics.width * 0.72,
      borderRadius: metrics.width,
      backgroundColor: 'rgba(201,29,36,0.22)',
    },
    screenGlowBottom: {
      position: 'absolute',
      bottom: -metrics.height * 0.18,
      left: -metrics.width * 0.22,
      width: metrics.width * 0.66,
      height: metrics.width * 0.66,
      borderRadius: metrics.width,
      backgroundColor: 'rgba(255,255,255,0.045)',
    },
    topBar: {
      minHeight: control.headerHeight,
      marginHorizontal: horizontalPadding,
      paddingHorizontal: spacing.sm,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      borderRadius: radius.xl,
      borderWidth: border.thin,
      borderColor: 'rgba(255,255,255,0.12)',
      backgroundColor: 'rgba(8,8,11,0.96)',
      shadowColor: '#C91D24',
      shadowOpacity: 0.24,
      shadowOffset: {width: 0, height: 12},
      shadowRadius: spacing.lg,
      elevation: 14,
      zIndex: 5,
    },
    headerSide: {
      width: isWide ? 158 : 104,
      flexDirection: 'row',
      alignItems: 'center',
    },
    headerSideRight: {
      justifyContent: 'flex-end',
    },
    headerTitleWrap: {
      flex: 1,
      alignItems: 'center',
      justifyContent: 'center',
      paddingHorizontal: spacing.xs,
    },
    headerTitle: {
      color: '#FFFFFF',
      fontSize: font.title,
      fontWeight: '900',
      textAlign: 'center',
    },
    headerSubTitle: {
      color: 'rgba(255,255,255,0.58)',
      fontSize: font.small,
      fontWeight: '800',
      marginTop: spacing.xxs,
      textAlign: 'center',
    },
    headerAuthCenter: {
      flex: 1,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      columnGap: spacing.sm,
    },
    headerAuthButton: {
      minHeight: control.minTouch,
      paddingHorizontal: isCompact ? spacing.sm : spacing.md,
      borderRadius: radius.pill,
      borderWidth: border.thin,
      borderColor: 'rgba(255,255,255,0.22)',
      backgroundColor: '#C91D24',
      alignItems: 'center',
      justifyContent: 'center',
      shadowColor: '#FF2B2B',
      shadowOpacity: 0.26,
      shadowOffset: {width: 0, height: 8},
      shadowRadius: spacing.sm,
      elevation: 6,
    },
    headerAuthButtonSecondary: {
      minHeight: control.minTouch,
      paddingHorizontal: isCompact ? spacing.sm : spacing.md,
      borderRadius: radius.pill,
      borderWidth: border.thin,
      borderColor: 'rgba(255,255,255,0.14)',
      backgroundColor: 'rgba(255,255,255,0.07)',
      alignItems: 'center',
      justifyContent: 'center',
    },
    headerAuthText: {
      color: '#FFFFFF',
      fontSize: isCompact ? font.small : font.body,
      fontWeight: '900',
    },
    backButton: {
      minHeight: control.minTouch,
      borderRadius: radius.pill,
      borderWidth: border.thin,
      borderColor: 'rgba(255,255,255,0.14)',
      backgroundColor: 'rgba(255,255,255,0.06)',
      alignItems: 'center',
      justifyContent: 'center',
      paddingHorizontal: spacing.sm,
    },
    backText: {
      color: '#FFFFFF',
      fontSize: font.body,
      fontWeight: '900',
    },
    headerLogo: {
      width: isWide ? icon.xl * 2.25 : icon.xl * 1.7,
      height: isWide ? icon.xl * 1.2 : icon.xl,
    },
    notice: {
      marginHorizontal: horizontalPadding,
      marginTop: spacing.sm,
      borderRadius: radius.lg,
      backgroundColor: 'rgba(0, 201, 94, 0.13)',
      borderWidth: border.thin,
      borderColor: 'rgba(0, 201, 94, 0.32)',
      padding: spacing.sm,
      zIndex: 4,
    },
    noticeText: {
      color: '#D8FFF5',
      fontSize: font.body,
      fontWeight: '800',
    },
    errorNotice: {
      backgroundColor: 'rgba(255, 40, 40, 0.13)',
      borderColor: 'rgba(255, 40, 40, 0.38)',
    },
    customerShell: {
      flex: 1,
      flexDirection: 'row',
      paddingHorizontal: horizontalPadding,
      paddingTop: spacing.md,
      paddingBottom: spacing.sm,
      columnGap: spacing.md,
    },
    categoryColumn: {
      width: categoryWidth,
      borderRadius: radius.xl,
      borderWidth: border.thin,
      borderColor: 'rgba(255,255,255,0.10)',
      backgroundColor: 'rgba(8,8,12,0.96)',
      overflow: 'hidden',
      shadowColor: '#000',
      shadowOpacity: 0.5,
      shadowOffset: {width: 0, height: 14},
      shadowRadius: spacing.lg,
      elevation: 9,
    },
    categoryHeader: {
      paddingHorizontal: spacing.md,
      paddingVertical: spacing.md,
      borderBottomWidth: border.thin,
      borderBottomColor: 'rgba(255,255,255,0.08)',
      backgroundColor: 'rgba(255,255,255,0.035)',
    },
    categoryTitle: {
      color: '#FFFFFF',
      fontSize: font.label,
      fontWeight: '900',
    },
    categorySubtitle: {
      color: 'rgba(255,255,255,0.50)',
      fontSize: font.small,
      fontWeight: '700',
      marginTop: spacing.xxs,
    },
    categoryListContent: {
      padding: spacing.sm,
      paddingBottom: spacing.lg,
    },
    categoryItem: {
      minHeight: control.minTouch + spacing.xs,
      borderRadius: radius.lg,
      borderWidth: border.thin,
      borderColor: 'rgba(255,255,255,0.08)',
      backgroundColor: '#111116',
      paddingHorizontal: spacing.sm,
      justifyContent: 'center',
      marginBottom: spacing.sm,
    },
    categoryItemActive: {
      backgroundColor: '#C91D24',
      borderColor: 'rgba(255,255,255,0.32)',
      shadowColor: '#FF2B2B',
      shadowOpacity: 0.34,
      shadowOffset: {width: 0, height: 10},
      shadowRadius: spacing.md,
      elevation: 10,
    },
    categoryItemText: {
      color: '#FFFFFF',
      fontSize: isCompact ? font.body : font.bodyLarge,
      fontWeight: '900',
    },
    categoryCountText: {
      color: 'rgba(255,255,255,0.64)',
      fontSize: font.small,
      fontWeight: '800',
      marginTop: spacing.xxs,
    },
    menuColumn: {
      flex: 1,
      borderRadius: radius.xl,
      borderWidth: border.thin,
      borderColor: 'rgba(255,255,255,0.10)',
      backgroundColor: 'rgba(12,12,16,0.95)',
      overflow: 'hidden',
      shadowColor: '#000',
      shadowOpacity: 0.5,
      shadowOffset: {width: 0, height: 14},
      shadowRadius: spacing.lg,
      elevation: 9,
    },
    menuColumnHeader: {
      paddingHorizontal: spacing.md,
      paddingVertical: spacing.md,
      borderBottomWidth: border.thin,
      borderBottomColor: 'rgba(255,255,255,0.08)',
      backgroundColor: 'rgba(255,255,255,0.035)',
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      columnGap: spacing.sm,
    },
    menuTitleBlock: {
      flex: 1,
    },
    menuColumnTitle: {
      color: '#FFFFFF',
      fontSize: font.label,
      fontWeight: '900',
    },
    menuColumnHint: {
      color: 'rgba(255,255,255,0.56)',
      fontSize: font.small,
      fontWeight: '700',
      marginTop: spacing.xxs,
    },
    menuCountPill: {
      color: '#FFFFFF',
      fontSize: font.small,
      fontWeight: '900',
      backgroundColor: 'rgba(201,29,36,0.84)',
      paddingHorizontal: spacing.sm,
      paddingVertical: spacing.xxs,
      borderRadius: radius.pill,
      overflow: 'hidden',
    },
    menuGridContent: {
      padding: spacing.md,
      paddingBottom: spacing.xxl * 3.2,
    },
    menuGrid: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      justifyContent: 'space-between',
      rowGap: spacing.md,
    },
    dishCard: {
      width: dishCardWidth as any,
      borderRadius: radius.xl,
      borderWidth: border.thin,
      borderColor: 'rgba(255,255,255,0.10)',
      backgroundColor: '#15151A',
      overflow: 'hidden',
      shadowColor: '#000',
      shadowOpacity: 0.42,
      shadowOffset: {width: 0, height: 12},
      shadowRadius: spacing.md,
      elevation: 8,
    },
    adminDishCard: {
      width: adminDishCardWidth as any,
      borderRadius: radius.xl,
      borderWidth: border.thin,
      borderColor: 'rgba(255,255,255,0.10)',
      backgroundColor: '#15151A',
      overflow: 'hidden',
      shadowColor: '#000',
      shadowOpacity: 0.35,
      shadowOffset: {width: 0, height: 10},
      shadowRadius: spacing.md,
      elevation: 7,
    },
    dishImageWrap: {
      height: dishImageHeight,
      margin: spacing.sm,
      marginBottom: 0,
      borderRadius: radius.lg,
      overflow: 'hidden',
      backgroundColor: '#22222A',
      alignItems: 'center',
      justifyContent: 'center',
      borderWidth: border.thin,
      borderColor: 'rgba(255,255,255,0.08)',
    },
    dishImage: {
      width: '100%',
      height: '100%',
    },
    dishImageShade: {
      position: 'absolute',
      left: 0,
      right: 0,
      bottom: 0,
      height: '42%',
      backgroundColor: 'rgba(0,0,0,0.32)',
    },
    dishCategoryLabel: {
      position: 'absolute',
      left: spacing.sm,
      bottom: spacing.sm,
      color: '#FFFFFF',
      fontSize: font.small,
      fontWeight: '900',
      backgroundColor: 'rgba(0,0,0,0.58)',
      paddingHorizontal: spacing.sm,
      paddingVertical: spacing.xxs,
      borderRadius: radius.pill,
      overflow: 'hidden',
    },
    dishBody: {
      padding: spacing.sm,
      paddingTop: spacing.xs,
    },
    dishName: {
      color: '#FFFFFF',
      fontSize: font.bodyLarge,
      fontWeight: '900',
    },
    dishDescription: {
      color: 'rgba(255,255,255,0.62)',
      fontSize: font.small,
      lineHeight: font.small * 1.42,
      marginTop: spacing.xxs,
      minHeight: font.small * 2.8,
    },
    dishFooter: {
      marginTop: spacing.sm,
      flexDirection: isCompact ? 'column' : 'row',
      alignItems: isCompact ? 'stretch' : 'center',
      justifyContent: 'space-between',
      rowGap: spacing.xs,
      columnGap: spacing.sm,
    },
    dishPrice: {
      color: '#FF4C4C',
      fontSize: font.bodyLarge,
      fontWeight: '900',
    },
    addButton: {
      minHeight: control.minTouch,
      borderRadius: radius.pill,
      backgroundColor: '#C91D24',
      paddingHorizontal: spacing.md,
      alignItems: 'center',
      justifyContent: 'center',
      shadowColor: '#FF2B2B',
      shadowOpacity: 0.24,
      shadowOffset: {width: 0, height: 7},
      shadowRadius: spacing.sm,
      elevation: 6,
    },
    addButtonText: {
      color: '#FFFFFF',
      fontSize: font.body,
      fontWeight: '900',
    },
    disabledText: {
      color: 'rgba(255,255,255,0.48)',
      fontSize: font.body,
      fontWeight: '900',
    },
    quantityControl: {
      minHeight: control.minTouch,
      borderRadius: radius.pill,
      borderWidth: border.thin,
      borderColor: 'rgba(255,80,80,0.42)',
      backgroundColor: 'rgba(201,29,36,0.18)',
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      paddingHorizontal: spacing.xs,
      columnGap: spacing.sm,
    },
    quantityButton: {
      width: control.minTouch - spacing.xs,
      height: control.minTouch - spacing.xs,
      borderRadius: radius.pill,
      backgroundColor: '#C91D24',
      alignItems: 'center',
      justifyContent: 'center',
    },
    quantityButtonText: {
      color: '#FFFFFF',
      fontSize: font.label,
      fontWeight: '900',
      lineHeight: font.label * 1.15,
    },
    quantityText: {
      minWidth: spacing.lg,
      color: '#FFFFFF',
      fontSize: font.bodyLarge,
      fontWeight: '900',
      textAlign: 'center',
    },
    quantityTextSmall: {
      minWidth: spacing.lg,
      color: '#FFFFFF',
      fontSize: font.body,
      fontWeight: '900',
      textAlign: 'center',
    },
    quantityControlSmall: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      columnGap: spacing.xs,
      marginTop: spacing.xs,
    },
    quantityButtonSmall: {
      width: control.minTouch - spacing.sm,
      height: control.minTouch - spacing.sm,
      borderRadius: radius.pill,
      backgroundColor: '#C91D24',
      alignItems: 'center',
      justifyContent: 'center',
    },
    cartBottomBar: {
      position: 'absolute',
      right: horizontalPadding + spacing.md,
      bottom: safeArea.bottom + spacing.lg,
      width: isWide ? Math.min(430, metrics.width * 0.42) : metrics.width * 0.62,
      minHeight: control.buttonHeight + spacing.xs,
      borderRadius: radius.xl,
      backgroundColor: '#C91D24',
      borderWidth: border.thin,
      borderColor: 'rgba(255,255,255,0.24)',
      paddingLeft: spacing.md,
      paddingRight: spacing.md,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      columnGap: spacing.sm,
      shadowColor: '#FF2B2B',
      shadowOpacity: 0.45,
      shadowOffset: {width: 0, height: 12},
      shadowRadius: spacing.lg,
      elevation: 18,
      zIndex: 20,
    },
    cartBarIconWrap: {
      width: control.minTouch,
      height: control.minTouch,
      borderRadius: radius.pill,
      backgroundColor: 'rgba(0,0,0,0.22)',
      alignItems: 'center',
      justifyContent: 'center',
    },
    cartFloatingIcon: {
      color: '#FFFFFF',
      fontSize: font.label,
      fontWeight: '900',
    },
    cartFloatingText: {
      color: '#FFFFFF',
      fontSize: font.bodyLarge,
      fontWeight: '900',
    },
    cartBarMain: {
      flex: 1,
    },
    cartBarSubText: {
      color: 'rgba(255,255,255,0.76)',
      fontSize: font.small,
      fontWeight: '800',
      marginTop: spacing.xxs,
    },
    cartBarTotal: {
      color: '#FFFFFF',
      fontSize: font.bodyLarge,
      fontWeight: '900',
    },
    cartBadge: {
      position: 'absolute',
      top: -spacing.xs,
      right: -spacing.xs,
      minWidth: spacing.lg,
      height: spacing.lg,
      paddingHorizontal: spacing.xs,
      borderRadius: radius.pill,
      backgroundColor: '#FFFFFF',
      borderWidth: border.thin,
      borderColor: '#C91D24',
      alignItems: 'center',
      justifyContent: 'center',
    },
    cartBadgeText: {
      color: '#C91D24',
      fontSize: font.small,
      fontWeight: '900',
    },
    cartModalRoot: {
      ...StyleSheet.absoluteFillObject,
      width: '100%',
      height: '100%',
      zIndex: 9999,
      elevation: 9999,
      alignItems: 'stretch',
      justifyContent: 'flex-start',
      backgroundColor: 'rgba(0,0,0,0.94)',
    },
    cartModalDimLayer: {
      ...StyleSheet.absoluteFillObject,
      backgroundColor: 'rgba(0,0,0,0.94)',
    },
    cartModalKeyboardLayer: {
      flex: 1,
      width: '100%',
      height: '100%',
      alignSelf: 'stretch',
      paddingTop: safeArea.top + spacing.sm,
      paddingBottom: Math.max(safeArea.bottom, spacing.sm),
      paddingHorizontal: 0,
      alignItems: 'stretch',
      justifyContent: 'flex-start',
      backgroundColor: 'transparent',
    },
    cartModalCard: {
      flex: 1,
      width: '100%',
      height: '100%',
      alignSelf: 'stretch',
      borderRadius: 0,
      borderWidth: 0,
      borderColor: 'transparent',
      backgroundColor: '#08080B',
      overflow: 'hidden',
      shadowColor: '#000000',
      shadowOpacity: 0,
      shadowOffset: {width: 0, height: 0},
      shadowRadius: 0,
      elevation: 0,
    },
    cartModalHeader: {
      width: '100%',
      paddingHorizontal: spacing.md,
      paddingVertical: spacing.md,
      borderBottomWidth: border.thin,
      borderBottomColor: 'rgba(255,255,255,0.10)',
      backgroundColor: 'rgba(255,255,255,0.035)',
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      columnGap: spacing.md,
    },
    cartModalTitle: {
      color: '#FFFFFF',
      fontSize: font.title,
      fontWeight: '900',
    },
    cartModalSubTitle: {
      color: 'rgba(255,255,255,0.58)',
      fontSize: font.small,
      fontWeight: '800',
      marginTop: spacing.xxs,
    },
    closeButton: {
      minWidth: control.minTouch,
      minHeight: control.minTouch,
      borderRadius: radius.pill,
      borderWidth: border.thin,
      borderColor: 'rgba(255,255,255,0.14)',
      backgroundColor: 'rgba(255,255,255,0.07)',
      paddingHorizontal: spacing.md,
      alignItems: 'center',
      justifyContent: 'center',
    },
    closeButtonText: {
      color: '#FFFFFF',
      fontSize: font.label,
      fontWeight: '900',
    },
    cartList: {
      flex: 1,
      width: '100%',
      alignSelf: 'stretch',
    },
    cartListContent: {
      width: '100%',
      padding: spacing.md,
      paddingBottom: spacing.md,
    },
    cartModalFooter: {
      width: '100%',
      alignSelf: 'stretch',
      borderTopWidth: border.thin,
      borderTopColor: 'rgba(255,255,255,0.10)',
      backgroundColor: '#101014',
      paddingHorizontal: spacing.md,
      paddingTop: spacing.sm,
      paddingBottom: spacing.md,
      rowGap: spacing.sm,
    },
    cartRow: {
      borderRadius: radius.lg,
      borderWidth: border.thin,
      borderColor: 'rgba(255,255,255,0.10)',
      backgroundColor: '#15151A',
      padding: spacing.sm,
      marginBottom: spacing.sm,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      columnGap: spacing.md,
    },
    cartRowMain: {
      flex: 1,
    },
    cartRowRight: {
      alignItems: 'flex-end',
    },
    cartItemName: {
      color: '#FFFFFF',
      fontSize: font.bodyLarge,
      fontWeight: '900',
    },
    cartMeta: {
      color: 'rgba(255,255,255,0.60)',
      fontSize: font.small,
      fontWeight: '700',
      marginTop: spacing.xxs,
    },
    cartLineTotal: {
      color: '#FF4C4C',
      fontSize: font.bodyLarge,
      fontWeight: '900',
    },
    totalRow: {
      marginTop: spacing.sm,
      borderRadius: radius.lg,
      borderWidth: border.thin,
      borderColor: 'rgba(255,80,80,0.30)',
      backgroundColor: 'rgba(201,29,36,0.14)',
      padding: spacing.md,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
    },
    totalLabel: {
      color: 'rgba(255,255,255,0.70)',
      fontSize: font.body,
      fontWeight: '800',
    },
    totalValue: {
      color: '#FFFFFF',
      fontSize: font.label,
      fontWeight: '900',
    },
    inputWrap: {
      width: '100%',
      alignSelf: 'stretch',
      borderRadius: radius.lg,
      borderWidth: border.thin,
      borderColor: 'rgba(255,255,255,0.11)',
      backgroundColor: '#15151A',
      paddingHorizontal: spacing.sm,
      paddingTop: spacing.xs,
    },
    inputWrapError: {
      borderColor: '#FF4C4C',
      backgroundColor: 'rgba(255,40,40,0.12)',
    },
    inputLabel: {
      color: 'rgba(255,255,255,0.58)',
      fontSize: font.small,
      fontWeight: '900',
      letterSpacing: 0.5,
    },
    input: {
      minHeight: control.fieldHeight,
      color: '#FFFFFF',
      fontSize: font.bodyLarge,
      fontWeight: '800',
      paddingVertical: 0,
    },
    textArea: {
      minHeight: control.fieldHeight + spacing.md,
      color: '#FFFFFF',
      fontSize: font.body,
      fontWeight: '800',
      textAlignVertical: 'top',
      paddingTop: spacing.xs,
      paddingBottom: spacing.sm,
    },
    fieldErrorText: {
      color: '#FF6868',
      fontSize: font.small,
      fontWeight: '900',
      marginTop: -spacing.xs,
      marginLeft: spacing.xs,
    },
    primaryButton: {
      width: '100%',
      alignSelf: 'stretch',
      minHeight: control.buttonHeight,
      borderRadius: radius.pill,
      backgroundColor: '#C91D24',
      alignItems: 'center',
      justifyContent: 'center',
      paddingHorizontal: spacing.md,
      borderWidth: border.thin,
      borderColor: 'rgba(255,255,255,0.22)',
      shadowColor: '#FF2B2B',
      shadowOpacity: 0.24,
      shadowOffset: {width: 0, height: 8},
      shadowRadius: spacing.sm,
      elevation: 6,
    },
    primaryButtonText: {
      color: '#FFFFFF',
      fontSize: font.body,
      fontWeight: '900',
    },
    secondaryButton: {
      minHeight: control.buttonHeight,
      borderRadius: radius.pill,
      backgroundColor: 'rgba(255,255,255,0.07)',
      borderWidth: border.thin,
      borderColor: 'rgba(255,255,255,0.14)',
      alignItems: 'center',
      justifyContent: 'center',
      paddingHorizontal: spacing.md,
    },
    secondaryButtonSmall: {
      minHeight: control.minTouch,
      borderRadius: radius.pill,
      backgroundColor: 'rgba(255,255,255,0.07)',
      borderWidth: border.thin,
      borderColor: 'rgba(255,255,255,0.14)',
      alignItems: 'center',
      justifyContent: 'center',
      paddingHorizontal: spacing.md,
    },
    secondaryButtonText: {
      color: '#FFFFFF',
      fontSize: font.body,
      fontWeight: '900',
    },
    dangerButtonSmall: {
      minHeight: control.minTouch,
      borderRadius: radius.pill,
      backgroundColor: 'rgba(255,50,50,0.16)',
      borderWidth: border.thin,
      borderColor: 'rgba(255,80,80,0.36)',
      alignItems: 'center',
      justifyContent: 'center',
      paddingHorizontal: spacing.md,
    },
    dangerButtonText: {
      color: '#FF7777',
      fontSize: font.body,
      fontWeight: '900',
    },
    emptyState: {
      width: '100%',
      borderRadius: radius.xl,
      borderWidth: border.thin,
      borderColor: 'rgba(255,255,255,0.10)',
      backgroundColor: 'rgba(255,255,255,0.04)',
      alignItems: 'center',
      justifyContent: 'center',
      padding: spacing.xl,
      minHeight: isShort ? 150 : 220,
    },
    emptyIcon: {
      fontSize: font.titleLarge,
      marginBottom: spacing.xs,
    },
    emptyText: {
      color: '#FFFFFF',
      fontSize: font.label,
      fontWeight: '900',
      textAlign: 'center',
    },
    emptySubText: {
      color: 'rgba(255,255,255,0.58)',
      fontSize: font.body,
      fontWeight: '700',
      marginTop: spacing.xs,
      textAlign: 'center',
    },
    adminScroll: {
      flex: 1,
    },
    adminScrollContent: {
      paddingHorizontal: horizontalPadding,
      paddingTop: spacing.md,
      paddingBottom: safeArea.bottom + spacing.xxl,
      rowGap: spacing.md,
    },
    authScrollContent: {
      paddingHorizontal: horizontalPadding,
      paddingTop: spacing.xl,
      paddingBottom: safeArea.bottom + spacing.xxl,
      alignItems: 'center',
    },
    authHero: {
      width: '100%',
      maxWidth: 760,
      borderRadius: radius.xl,
      borderWidth: border.thin,
      borderColor: 'rgba(255,80,80,0.24)',
      backgroundColor: 'rgba(201,29,36,0.14)',
      padding: spacing.lg,
      marginBottom: spacing.md,
    },
    authCard: {
      width: '100%',
      maxWidth: 760,
      borderRadius: radius.xl,
      borderWidth: border.thin,
      borderColor: 'rgba(255,255,255,0.10)',
      backgroundColor: 'rgba(13,13,17,0.96)',
      padding: spacing.md,
      shadowColor: '#000',
      shadowOpacity: 0.36,
      shadowOffset: {width: 0, height: 12},
      shadowRadius: spacing.lg,
      elevation: 7,
    },
    authLinkRow: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      alignItems: 'center',
      justifyContent: 'space-between',
      gap: spacing.sm,
      marginTop: spacing.md,
    },
    authTextButton: {
      minHeight: control.minTouch,
      justifyContent: 'center',
    },
    authTextButtonText: {
      color: '#FF6A6A',
      fontSize: font.body,
      fontWeight: '900',
    },
    loginEyebrow: {
      color: '#FF6A6A',
      fontSize: font.small,
      fontWeight: '900',
      letterSpacing: 0.6,
      textTransform: 'uppercase',
    },
    loginTitle: {
      color: '#FFFFFF',
      fontSize: font.titleLarge,
      fontWeight: '900',
      marginTop: spacing.xs,
    },
    loginHint: {
      color: 'rgba(255,255,255,0.68)',
      fontSize: font.body,
      fontWeight: '700',
      marginTop: spacing.xs,
      lineHeight: font.body * 1.4,
    },
    dashboardHero: {
      borderRadius: radius.xl,
      borderWidth: border.thin,
      borderColor: 'rgba(255,80,80,0.24)',
      backgroundColor: 'rgba(201,29,36,0.14)',
      padding: spacing.lg,
      marginBottom: spacing.md,
    },
    section: {
      borderRadius: radius.xl,
      borderWidth: border.thin,
      borderColor: 'rgba(255,255,255,0.10)',
      backgroundColor: 'rgba(13,13,17,0.95)',
      padding: spacing.md,
      marginBottom: spacing.md,
      shadowColor: '#000',
      shadowOpacity: 0.36,
      shadowOffset: {width: 0, height: 12},
      shadowRadius: spacing.lg,
      elevation: 7,
    },
    sectionHeader: {
      flexDirection: 'row',
      alignItems: 'flex-start',
      justifyContent: 'space-between',
      marginBottom: spacing.md,
      columnGap: spacing.md,
    },
    sectionHeaderText: {
      flex: 1,
    },
    sectionTitle: {
      color: '#FFFFFF',
      fontSize: font.label,
      fontWeight: '900',
    },
    sectionHint: {
      color: 'rgba(255,255,255,0.58)',
      fontSize: font.body,
      fontWeight: '700',
      marginTop: spacing.xxs,
      lineHeight: font.body * 1.35,
    },
    blockLabel: {
      color: '#FFFFFF',
      fontSize: font.bodyLarge,
      fontWeight: '900',
      marginTop: spacing.md,
      marginBottom: spacing.sm,
    },
    adminTabs: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      padding: spacing.xs,
      borderRadius: radius.pill,
      borderWidth: border.thin,
      borderColor: 'rgba(255,255,255,0.10)',
      backgroundColor: 'rgba(255,255,255,0.045)',
      marginBottom: spacing.md,
      columnGap: spacing.xs,
    },
    adminTab: {
      flex: 1,
      minHeight: control.minTouch,
      borderRadius: radius.pill,
      alignItems: 'center',
      justifyContent: 'center',
      paddingHorizontal: spacing.xs,
    },
    adminTabActive: {
      backgroundColor: '#C91D24',
      shadowColor: '#FF2B2B',
      shadowOpacity: 0.22,
      shadowOffset: {width: 0, height: 6},
      shadowRadius: spacing.sm,
      elevation: 5,
    },
    adminTabText: {
      color: 'rgba(255,255,255,0.72)',
      fontSize: font.body,
      fontWeight: '900',
    },
    adminTabTextActive: {
      color: '#FFFFFF',
      fontSize: font.body,
      fontWeight: '900',
    },
    formGrid: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      justifyContent: 'space-between',
      rowGap: spacing.sm,
    },
    formField: {
      width: isWide ? '49%' : '100%',
    },
    fullField: {
      width: '100%',
      marginBottom: spacing.sm,
    },
    formActions: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      alignItems: 'center',
      gap: spacing.sm,
      marginTop: spacing.md,
    },
    categorySelector: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: spacing.sm,
    },
    formCategoryChip: {
      minHeight: control.minTouch,
      borderRadius: radius.pill,
      paddingHorizontal: spacing.md,
      borderWidth: border.thin,
      borderColor: 'rgba(255,255,255,0.12)',
      backgroundColor: 'rgba(255,255,255,0.06)',
      alignItems: 'center',
      justifyContent: 'center',
    },
    formCategoryChipActive: {
      backgroundColor: '#C91D24',
      borderColor: 'rgba(255,255,255,0.26)',
    },
    formCategoryChipText: {
      color: 'rgba(255,255,255,0.76)',
      fontSize: font.body,
      fontWeight: '900',
    },
    formCategoryChipTextActive: {
      color: '#FFFFFF',
      fontSize: font.body,
      fontWeight: '900',
    },
    availabilityRow: {
      marginTop: spacing.md,
      borderRadius: radius.lg,
      borderWidth: border.thin,
      borderColor: 'rgba(255,255,255,0.10)',
      backgroundColor: 'rgba(255,255,255,0.04)',
      padding: spacing.md,
      flexDirection: 'row',
      alignItems: 'center',
      columnGap: spacing.md,
    },
    adminMenuGrid: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      justifyContent: 'space-between',
      rowGap: spacing.md,
    },
    adminDishMetaRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      columnGap: spacing.sm,
      marginTop: spacing.sm,
      marginBottom: spacing.sm,
    },
    adminCardActionsInline: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: spacing.sm,
    },
    categoryManageList: {
      rowGap: spacing.sm,
    },
    categoryManageRow: {
      borderRadius: radius.lg,
      borderWidth: border.thin,
      borderColor: 'rgba(255,255,255,0.10)',
      backgroundColor: '#15151A',
      padding: spacing.sm,
      flexDirection: isCompact ? 'column' : 'row',
      alignItems: isCompact ? 'stretch' : 'center',
      justifyContent: 'space-between',
      rowGap: spacing.sm,
      columnGap: spacing.md,
    },
    categoryManageInfo: {
      flex: 1,
    },
    categoryManageName: {
      color: '#FFFFFF',
      fontSize: font.bodyLarge,
      fontWeight: '900',
    },
    orderCard: {
      borderRadius: radius.xl,
      borderWidth: border.thin,
      borderColor: 'rgba(255,255,255,0.10)',
      backgroundColor: '#15151A',
      padding: spacing.md,
      marginBottom: spacing.md,
    },
    orderHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      columnGap: spacing.md,
    },
    orderTitle: {
      color: '#FFFFFF',
      fontSize: font.label,
      fontWeight: '900',
    },
    orderTime: {
      color: 'rgba(255,255,255,0.54)',
      fontSize: font.small,
      fontWeight: '800',
      marginTop: spacing.xxs,
    },
    statusPill: {
      borderRadius: radius.pill,
      paddingHorizontal: spacing.sm,
      paddingVertical: spacing.xxs,
      borderWidth: border.thin,
      borderColor: 'rgba(255,255,255,0.16)',
    },
    statusText: {
      color: '#FFFFFF',
      fontSize: font.small,
      fontWeight: '900',
    },
    orderItemsWrap: {
      marginTop: spacing.md,
      rowGap: spacing.xs,
    },
    orderItemText: {
      color: 'rgba(255,255,255,0.82)',
      fontSize: font.body,
      fontWeight: '800',
      lineHeight: font.body * 1.4,
    },
    orderNote: {
      color: '#FFD3D3',
      fontSize: font.body,
      fontWeight: '800',
      marginTop: spacing.sm,
    },
    orderFooter: {
      marginTop: spacing.md,
      alignItems: 'flex-end',
    },
    statusActions: {
      paddingTop: spacing.md,
      gap: spacing.sm,
    },
    statusButton: {
      minHeight: control.minTouch,
      borderRadius: radius.pill,
      borderWidth: border.thin,
      borderColor: 'rgba(255,255,255,0.12)',
      backgroundColor: 'rgba(255,255,255,0.06)',
      paddingHorizontal: spacing.md,
      alignItems: 'center',
      justifyContent: 'center',
    },
    statusButtonActive: {
      backgroundColor: '#C91D24',
      borderColor: 'rgba(255,255,255,0.26)',
    },
    statusButtonText: {
      color: 'rgba(255,255,255,0.76)',
      fontSize: font.body,
      fontWeight: '900',
    },
    statusButtonTextActive: {
      color: '#FFFFFF',
      fontSize: font.body,
      fontWeight: '900',
    },
  });
};

export default createStyles;
